# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wA5nl4DttyWEb5gketESvnSbEMlN9CV5
"""

import streamlit as st
import pandas as pd
import joblib

# Page configuration
st.set_page_config(
    page_title="ML Prediction Dashboard",
    layout="wide"
)

st.title("📊 Machine Learning Prediction Dashboard")
st.write("Upload your data and get predictions using the trained model.")

# Load model
@st.cache_resource
def load_model():
    model = joblib.load("model.pkl")
    return model

model = load_model()

# File upload
uploaded_file = st.file_uploader("Upload CSV file for prediction", type=["csv"])

if uploaded_file is not None:

    data = pd.read_csv(uploaded_file)

    st.subheader("Uploaded Data")
    st.dataframe(data)

    if st.button("Run Prediction"):

        predictions = model.predict(data)

        result = data.copy()
        result["Prediction"] = predictions

        st.subheader("Prediction Results")
        st.dataframe(result)

        csv = result.to_csv(index=False).encode("utf-8")

        st.download_button(
            label="Download Predictions",
            data=csv,
            file_name="predictions.csv",
            mime="text/csv",
        )

else:
    st.info("Please upload a CSV file to start predictions.")

# Sidebar info
st.sidebar.header("About Model")
st.sidebar.write("Model Type: Gradient Boosting Classifier")
st.sidebar.write("Framework: Scikit-Learn")